package util;

import util.dbg.*;

import java.util.*;

/**
 * Manager for generating uniqueid:s (within the life span of the present virtual machine
 * reincarnation), based on appending running numbers to a base string.
 */ 
public class IdManager {
    
    private HashMap mIdCountByBaseId = new HashMap();    
    
    //* Generates an String id that is unique among the id:s generated by this IdManager */    
    public String generateId(String pBaseId) {
        Integer oldCount = (Integer)mIdCountByBaseId.get(pBaseId);
        if (oldCount == null) {
            oldCount = new Integer(0);
        }
        
        int newCount = oldCount.intValue()+1;
        mIdCountByBaseId.put(pBaseId, new Integer(newCount));
        return pBaseId+newCount;        
    }

    public static void main (String[] args) {
        IdManager manager = new IdManager();
        String baseId = "ID_";
        // ArrayList ids = new ArrayList();
        int count = 10;
        while(count >0) {
            String id = manager.generateId(baseId);
            dbgMsg("Generated id: "+id);
             count--;
        }
    }
    
    private static void dbgMsg(String pMsg) {
        Logger.dbg("IdManager: "+pMsg);
    }
    
    
}
 
